---
- name: Get a list of plugins that need updating
  shell: "wp plugin status | grep '^ U' | tr -s ' ' | cut -f 3 -d ' '"
  args:
    chdir: "{{ webroot }}"
  register: plugins_needing_upgrade
  changed_when: false
  failed_when: false
  when: cms == 'WordPress' and contract_type is search("WordPress Maintenance")

- name: Set module variable to plugin
  set_fact:
    module_type: "plugin"

- name: Update plugins
  include_tasks:
    file: update-module.yml
  loop: "{{ plugins_needing_upgrade.stdout_lines }}"
  when: plugins_needing_upgrade.stdout_lines is defined

- name: Get a list of themes that need updating
  shell: "wp theme status | grep '^ U' | tr -s ' ' | cut -f 3 -d ' '"
  args:
    chdir: "{{ webroot }}"
  register: themes_needing_upgrade
  changed_when: false
  failed_when: false
  when: cms == 'WordPress' and contract_type is search("WordPress Maintenance")

- name: Set module variable to theme
  set_fact:
    module_type: "theme"

- name: Update themes
  include_tasks:
    file: update-module.yml
  loop: "{{ themes_needing_upgrade.stdout_lines }}"
  when: themes_needing_upgrade.stdout_lines is defined
