---
# TODO: Merge with regular update-module.yml
- name: Update a single plugin/theme (via install)
  command: "wp {{ module_type }} install /tmp/{{ item }}.zip --force"
  args:
    chdir: "{{ webroot }}"
  become: yes
  become_user: "{{ run_as_user }}"
  tags: upgrade-plugins

- name: Get the new plugin/theme version number
  shell: "wp {{ module_type }} list --format=csv | grep ^{{ item }} | cut -d ',' -f 4 "
  args:
    chdir: "{{ webroot }}"
  register: new_version_number
  become: yes
  become_user: "{{ run_as_user }}"
  tags: upgrade-plugins

- name: git add the plugin/theme
  command: git add -v -A
  args:
    chdir: "{{ webroot }}"
  register: add_result
  become: yes
  become_user: "{{ run_as_user }}"
  changed_when: add_result.stdout != ''
  failed_when: add_result.stderr != ''
  tags: upgrade-plugins

- name: git commit plugin/theme
  command: "git commit -m 'WP {{ module_type }} upgrade: {{ item }} {{ new_version_number.stdout }}'"
  args:
    chdir: "{{ webroot }}"
  register: commit_result
  become: yes
  become_user: "{{ run_as_user }}"
  changed_when: commit_result.rc == 0
  failed_when: not(commit_result.rc == 0 or 'nothing to commit, working tree clean' in commit_result.stdout_lines)
  tags: upgrade-plugins
