---
- name: Update a single plugin/theme (free) {{ item }}
  command: "wp {{ module_type }} update {{ item }}"
  args:
    chdir: "{{ webroot }}"
  become: yes
  become_user: "{{ run_as_user }}"
  register: update_result
  failed_when: not(update_result.rc == 0 or update_result.stderr is search("Update package not available."))
  tags: upgrade-plugins
  when: module_source == "normal"

- name: Update a single plugin/theme (paid, from zip file)
  command: "wp {{ module_type }} install /tmp/{{ item }}.zip --force"
  args:
    chdir: "{{ webroot }}"
  become: yes
  become_user: "{{ run_as_user }}"
  tags: upgrade-plugins
  when: module_source == "zip"

- name: Get the new plugin/theme version number
  shell: "wp {{ module_type }} list --format=csv | grep ^{{ item }} | cut -d ',' -f 4 "
  args:
    chdir: "{{ webroot }}"
  register: new_version_number
  become: yes
  become_user: "{{ run_as_user }}"
  tags: upgrade-plugins

- name: Apply patches to CiviCRM Profile Sync
  patch:
    src: "{{role_path}}/files/bp-profile-sync.diff"
    backup: false
    basedir: "{{ webroot }}/wp-content/plugins/civicrm-wp-profile-sync"
    strip: 1
  become: yes
  when: item == "civicrm-wp-profile-sync"
  
- name: git add the plugin/theme
  command: git add -v -A
  args:
    chdir: "{{ webroot }}"
  register: add_result
  become: yes
  become_user: "{{ run_as_user }}"
  changed_when: add_result.stdout != ''
  failed_when: add_result.stderr != ''
  tags: upgrade-plugins

- name: git commit plugin/theme
  command: "git commit -m 'WP {{ module_type }} upgrade: {{ item }} {{ new_version_number.stdout }}'"
  args:
    chdir: "{{ webroot }}"
  register: commit_result
  become: yes
  become_user: "{{ run_as_user }}"
  changed_when: commit_result.rc == 0
  failed_when: not(commit_result.rc == 0 or 'nothing to commit, working tree clean' in commit_result.stdout_lines)
  tags: upgrade-plugins
